"""Pydantic schemas for API validation and serialization"""
from app.schemas.common import (
    PaginatedResponse,
    SuccessResponse,
    ErrorResponse,
    HealthCheck,
    PaginationParams
)
from app.schemas.farm import FarmCreate, FarmUpdate, FarmInDB, FarmResponse, FarmListItem
from app.schemas.plot import PlotCreate, PlotUpdate, PlotInDB, PlotResponse, PlotListItem
from app.schemas.crop import CropCreate, CropUpdate, CropInDB, PlantingCreate, PlantingUpdate, PlantingInDB
from app.schemas.irrigation import IrrigationEventCreate, IrrigationEventUpdate, IrrigationEventInDB
from app.schemas.nutrient import NutrientApplicationCreate, NutrientApplicationUpdate, NutrientApplicationInDB
from app.schemas.import_job import (
    ImportJobCreate,
    ImportJobUpdate,
    ImportJobInDB,
    ImportJobResponse,
    ImportJobListItem,
    ImportErrorResponse,
    ImportTemplateCreate,
    ImportTemplateInDB,
    ImportTemplateResponse,
    ColumnMappingSuggestion,
    ColumnMappingRequest,
    ColumnMappingResponse,
    ValidationError,
    ValidationResultResponse,
    FileUploadResponse,
    DataPreviewResponse,
    ImportStatus,
    DataType,
)

__all__ = [
    "PaginatedResponse",
    "SuccessResponse",
    "ErrorResponse",
    "HealthCheck",
    "PaginationParams",
    "FarmCreate",
    "FarmUpdate",
    "FarmInDB",
    "FarmResponse",
    "FarmListItem",
    "PlotCreate",
    "PlotUpdate",
    "PlotInDB",
    "PlotResponse",
    "PlotListItem",
    "CropCreate",
    "CropUpdate",
    "CropInDB",
    "PlantingCreate",
    "PlantingUpdate",
    "PlantingInDB",
    "IrrigationEventCreate",
    "IrrigationEventUpdate",
    "IrrigationEventInDB",
    "NutrientApplicationCreate",
    "NutrientApplicationUpdate",
    "NutrientApplicationInDB",
    "ImportJobCreate",
    "ImportJobUpdate",
    "ImportJobInDB",
    "ImportJobResponse",
    "ImportJobListItem",
    "ImportErrorResponse",
    "ImportTemplateCreate",
    "ImportTemplateInDB",
    "ImportTemplateResponse",
    "ColumnMappingSuggestion",
    "ColumnMappingRequest",
    "ColumnMappingResponse",
    "ValidationError",
    "ValidationResultResponse",
    "FileUploadResponse",
    "DataPreviewResponse",
    "ImportStatus",
    "DataType",
]
